newIssueWelcomeComment: >
  â¤ï¸ Thanks for opening your first issue here! We will follow up as soon as we can.

newPRWelcomeComment: >
  ðŸ™Œ Thanks for your contribution! ðŸŽ‰ðŸ¥³ You're awesome.

firstPRMergeComment: >
  Congrats on merging your first pull request in this repository! ðŸ…

requestInfoReplyComment: >
  We would appreciate it if you could provide us with more information about this
  issue/pr. ðŸ™ˆ

requestInfoLabelToAdd: 'need more info'
